remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: TitanBot Robotics Project
description:


header_pages:
  - pages/currentdesign.md
  - pages/machinedesign.md
  - pages/software.md
  - pages/sensors.md
  - pages/about.md