theme: jekyll-theme-slate
title: Robotron's Powerplay Runner
description: This site shows a description of how I built my passion project and what I did to make my robot successful. 
url: https://ryancutinha.github.io
