remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Robotron Passion Project
description: My passion project involved building a robotic machine that can navigate through mazes and perform certain tasks. I am interested in engineering, and building this robotic machine has helped to expand my passion for engineering.
